# -*- python -*-

package(default_visibility = ["//visibility:public"])

exports_files([
    "config_servos.py",
    "performance_governor.sh",
    "quad-start.sh",
    "quad_screen.conf",
    "quad.cmd",
    "start-robot.sh",
    "zero_leg.py",
    "zero_motors.py",
    "tum_gui.py",
])

filegroup(
    name = "gui_assets",
    srcs = glob(["gui_assets/**/*"]),
)